---

- name: Install core requirements
  become: true
  become_user: pythondev
  pip:
    requirements: /home/pythondev/pythondev-site/requirements.txt
    executable: /home/pythondev/.pyvenv/bin/pip
  notify:
    - Restart pythondev-site
